### PR TITLE
observers 

### PR DESCRIPTION
**Pull request by suresh-kumara-gist**
Execute observers functionality:-

```
./scripts/node-cli.sh

await app.c('observerExamplePublisher').helloWorld();
```

In logs we can see output.

% docker compose logs node  
```
ObserverExamplePublisher is performing an action, and will trigger a publish.
 ____________handler___________________
 subscriber1
 hello
 ____________handler___________________
 subscriber2
 world
 ObserverExamplePublisher has published.
```

### CODE REVIEW

**Comment by alberto56** [comment]
I made some changes at https://github.com/dcycle/starterkit-node/pull/64/commits/d280563a765721bee5585be376f3a38f4dfc0f55

Now it is possible to subscribe only once if you want to, by specifying an ID.

Please look at the code.

Next step is to make this persistent in the database in case the app is restarted.

**Comment by suresh-kumara-gist** [comment]
I am storing subscribers to subscribers collections not sure where we need to fetch stored subscribers and make use of it. kindly review PR and suggest.

**Comment by suresh-kumara-gist** [comment]
```
  // publish the event for a specific event.
  async publish(publisherModule, publishedEvent, data) {
    if (!this.isModuleEnabled(publisherModule)) {
      return;
    }
    this.ensureStructureValid(
      publisherModule,
      publishedEvent,
    );

    // https://stackoverflow.com/a/7241901
    const subscribers = this.subscribers[publisherModule][publishedEvent];

    for (const subscriberId in subscribers) {
      if (subscribers.hasOwnProperty(subscriberId)) {
        const module = subscribers[subscriberId].subscriberModule;
        const method = subscribers[subscriberId].subscriberMethod;
        this.app().c(module)[method](data);
      }
    }
  }


```

In publish method     instead of 
```
const subscribers = this.subscribers[publisherModule][publishedEvent];
```

we need to fetch from observers collection. For that 


I have created observers schema 
```
    const Schema = app.component('./database/index.js').mongoose().Schema;

    // Subscription schema to hold the subscriptionModule
    // and subscriptionMethod
    const SubscriptionSchema = new Schema({
      subscriptionModule: { type: String, required: true },
      subscriptionMethod: { type: String, required: true },
    });

    // PublisherMethod schema to hold multiple subscriptions
    // with their respective IDs
    const publishedEventSchema = new Schema({
      // Dynamic keys to represent subscriptionId as a key-value pair
      subscriptionsId: {
        type: Map,
        of: SubscriptionSchema,
      },
    });

    // PublisherModule schema that holds multiple publisher methods
    const PublisherModuleSchema = new Schema({
      publishedEvent: {
        type: Map,
        of: publishedEventSchema,
      },
    });

    // Root schema to hold multiple publisher modules
    const ObserverSchema = new Schema({
      publisherModules: {
        type: Map,
        of: PublisherModuleSchema,
      },
    });

    this.observersModel = app.component('./database/index.js')
      .mongoose().model('observers', ObserverSchema);


```

I am trying out this schema . this where I am.

**Comment by suresh-kumara-gist** [comment]
In order to test this functionality :

First subscribe an helloWorld publishedEvent in ./scripts/node-cli.sh 

```
    await app.c('observer').subscribe(
      'observerExamplePublisher',
      'helloWorld',
      'observerExampleSubscriber',
      'subscriber2',
      'new-subscriber2',
    );

```
'new-subscriber2' is a subscriber Id , we are passing manually.  'new-subscriber2' is a subscriber Id is not present in observer collections. Hence Observer should get saved to database.

You can verify it by running below command.

```
    await app.c('observer').getAllObservers();
```

Now publish the helloWorld

```
    await app.c('observer').helloWorld();
```

terminate the node console and check node logs to see the response.

```
$ docker compose logs node 
```

there are few subscriber already subscribed to  helloWorld publishedEvent. Hence we might get response like.

```
hello
hello
world
world
```

**Pull request merged**
